### ISSUE TITLE
intermediate solution - weighted mis

### ISSUE THREAD

**Issue by simonenotarnicola** [KarlsruheMIS/KaMIS#33]
Is it possible to print the temporary solution at the end of each step of the weighted branch and reduce algorithm?

**Comment by darrenstrash** [comment]
Thank you for reaching out. I assume you would like to print out the independent set, and not just its size. It is actually nontrivial to do this, since we branch on different components. When the algorithm is searching a particular component, it does not have a solution for the entire graph. If you really want to do this, there are three things you can try, with various levels difficulty and potential slowdown to the algorithm.

- Print the solution in [`restore_best_global_solution()`](https://github.com/KarlsruheMIS/KaMIS/blob/96aef9c801786e49a75bf945256b42f7c0918a1f/wmis/lib/mis/kernel/branch_and_reduce_algorithm.cpp#LL652C2-L652C32). This won't print as often as you like, but it will print every time a better global solution is registered (after all connected components have finished). This is the least intrusive and shouldn't slow the algorithm down.

- You can add a call to [`restore_best_global_solution()`](https://github.com/KarlsruheMIS/KaMIS/blob/96aef9c801786e49a75bf945256b42f7c0918a1f/wmis/lib/mis/kernel/branch_and_reduce_algorithm.cpp#LL652C2-L652C32), after each component finishes [here](https://github.com/KarlsruheMIS/KaMIS/blob/96aef9c801786e49a75bf945256b42f7c0918a1f/wmis/lib/mis/kernel/branch_and_reduce_algorithm.cpp#L644) and print the solution there. This still won't print as often as you want, but it again shouldn't slow the algorithm down too much.

- To get a true solution after each step will slow the algorithm down significantly. However, if you really want to do this, there are a few ways. Firstly, you could disable solving components individually by setting [`SPLIT_CC_LIMIT`](https://github.com/KarlsruheMIS/KaMIS/blob/96aef9c801786e49a75bf945256b42f7c0918a1f/wmis/lib/mis/kernel/branch_and_reduce_algorithm.h#LL122C11-L122C11) to something very high, and then print the solution every time [`reverse_branching()`](https://github.com/KarlsruheMIS/KaMIS/blob/96aef9c801786e49a75bf945256b42f7c0918a1f/wmis/lib/mis/kernel/branch_and_reduce_algorithm.cpp#L555) is called. If you want to preserve component solving, you can modify `reverse_branching()` to update the global solution, similar to what is done [here](https://github.com/KarlsruheMIS/KaMIS/blob/96aef9c801786e49a75bf945256b42f7c0918a1f/wmis/lib/mis/kernel/branch_and_reduce_algorithm.cpp#LL633C1-L644C25) and then call `restore_best_global_solution()` to undo reductions and get a current global solution. Again, either of these options will slow the algorithm down significantly.

Please keep in touch and let us know if you have any success with these methods. As this is an enhancement, if we don't hear from you in a few weeks, I will close the issue.

**Comment by simonenotarnicola** [comment]
Thank you for your answer. in run_branch_reduce(), I added a call to restore_best_global_solution() after the initial_reduce() call and then after local_graph = nullptr; as you suggested. I see that calling multiple times restore_best_global_solution() causes a segmentation fault. how could I fix this? thank you in advance

**Comment by darrenstrash** [comment]
Hi @simonenotarnicola,

I think it's worth taking a step back; can I ask what the purpose of having the solution after each step is? Maybe we can find an alternative solution for you.

Here's advice if you wish to continue: `restore_best_global_solution()` is destructive (it calls `std::move`, which leaves `global_status` empty, and undoes reductions permanently). Instead of calling this function, consider making a version with the same functionality that does not destroy `global_status `and only undoes the reductions temporarily. Note that you can only call this function when there is actually a `global_status` to restore. It may not exist at these points where you added the call, it is really only used after components.

Note that these changes are getting into dangerous territory. I'm happy to continue to offer some advice from time to time on your journey, but I also can't anticipate all of the difficulties you will encounter. This is something we purposefully avoided in the implementation, as it is complex and will ultimately slow things down.
